--- # Publish all joint states --------------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

# Simple position controllers ------------------------------------
panda_j1_position_controller:
  type: effort_controllers/JointPositionController
  joint: panda_joint1
  pid: { p: 18000, i: 10, d: 25.0 }
panda_j2_position_controller:
  type: effort_controllers/JointPositionController
  joint: panda_joint2
  pid: { p: 18000, i: 10, d: 30.0 }
panda_j3_position_controller:
  type: effort_controllers/JointPositionController
  joint: panda_joint3
  pid: { p: 18000, i: 10, d: 30.0 }
panda_j4_position_controller:
  type: effort_controllers/JointPositionController
  joint: panda_joint4
  pid: { p: 18000, i: 10, d: 50.0 }
panda_j5_position_controller:
  type: effort_controllers/JointPositionController
  joint: panda_joint5
  pid: { p: 18000, i: 10, d: 8.0 }
panda_j6_position_controller:
  type: effort_controllers/JointPositionController
  joint: panda_joint6
  pid: { p: 18000, i: 10, d: 5.0 }
panda_j7_position_controller:
  type: effort_controllers/JointPositionController
  joint: panda_joint7
  pid: { p: 3000, i: 10, d: 4.0 }
